version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  development-deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:ff:5c:f9:5e:6f:49:66:36:3f:88:92:ab:29:82:f4"
      - run:
          command: |
            ssh ubuntu@ec2-18-188-66-115.us-east-2.compute.amazonaws.com "bash devPods.sh"
  approval-job:

  production-deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:ff:5c:f9:5e:6f:49:66:36:3f:88:92:ab:29:82:f4"
      - run:
          command: |
            ssh  ubuntu@ec2-18-188-66-115.us-east-2.compute.amazonaws.com "bash prodPods.sh"
workflows:
    build-and-test:
      jobs:
        - development-deploy
        - approval-job:
            type: approval
            requires:
              - development-deploy
        - production-deploy:
            requires:
              - approval-job
              